name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'

jobs:
  build:
    uses: onecx/ci-quarkus/.github/workflows/build.yml@v1
    secrets: inherit
    with:
      native: true
      helmEventTargetRepository: onecx/onecx-help
  trivy-manual:
    name: quarkus build and test
    runs-on: ubuntu-latest
    steps:
     - name: Run Trivy vulnerability scanner for app docker image
       continue-on-error: true
       uses: aquasecurity/trivy-action@0.28.0
       with:
        image-ref: 'ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:1.1.0-native'
        severity: 'HIGH,CRITICAL'
        format: table 


